// Code generated by protoc-gen-go-setters. DO NOT EDIT.
// source: example/example.proto
package example

func (x *ListExamplesRequest) SetPageToken(in string) {
	x.PageToken = in
}

func (x *ListExamplesResponse) SetNextPageToken(in string) {
	x.NextPageToken = in
}

func (x *Example) SetNum(in int32) {
	x.Num = in
}
